### ISSUE TITLE
How to run a script after 3 seconds delay using javascript?

### ISSUE THREAD

**Issue by almasdesign** [almasdesign/delay-in-JavaScript#1]
??

**Comment by aaghajani** [comment]
Hello my friend.
Using the following code snippet:
`var alertValue = "Lorem ipsum dolor sit amet, consectetur adipiscing elit..";
alert( alertValue );
setTimeout( function() { alert( alertValue ) }, 3000 );`

**Comment by almasdesign** [comment]
thanks a lot. The problem was solved :)
